[_meta]
[_meta.agtk]
managed = ['mcp_servers']

[mcp_servers]
[mcp_servers.context7]
args = ['-y', '@upstash/context7-mcp', '--api-key', '${CONTEXT7_KEY}']
command = 'npx'

[mcp_servers.context7.env]
DATABASE_URL = '${CONTEXT7_KEY}'

[mcp_servers.serena]
args = ['start-mcp-server', '--context', 'codex', '--project-from-cwd']
command = 'serena'
