package memory

import (
	"bytes"
	"errors"
	"fmt"
	"io/fs"
	"os"
)

// IndexHeader marks INDEX.md as generated. `agtk memory lint` fails when
// the file on disk differs from what RenderIndex produces, so the index can
// never drift from the notes and a merge conflict in it is resolved by
// regenerating rather than by hand.
const IndexHeader = "# Memory index\n\n" +
	"<!-- DO NOT EDIT — generated by `agtk memory index` from note frontmatter. -->\n"

// RenderIndex builds INDEX.md from note frontmatter alone.
//
// The index is the one file loaded on every session, so it carries only
// what routing needs: the name to fetch, the kind and confidence to triage
// on, one line of description for a question that does not yet name a file,
// and the anchor paths for a question that does. It deliberately omits
// staleness, which would make an unrelated one-line source edit produce an
// index diff in every PR.
func RenderIndex(notes []*Note) []byte {
	var b bytes.Buffer
	b.WriteString(IndexHeader)
	if len(notes) == 0 {
		b.WriteString("\n_No notes yet._\n")
		return b.Bytes()
	}
	noun := "notes"
	if len(notes) == 1 {
		noun = "note"
	}
	fmt.Fprintf(&b, "\n%d %s. Read one with `agtk memory show <name>`.\n", len(notes), noun)
	for _, n := range notes {
		fmt.Fprintf(&b, "\n## %s  (%s, %s)\n%s\n\n", n.Name, n.Kind, n.Confidence, n.Description)
		for _, a := range n.Anchors {
			// A list, not indented plain lines: INDEX.md is committed and
			// read in review, and lazy continuation would render every
			// anchor as part of the description paragraph.
			fmt.Fprintf(&b, "- %s\n", a.Path)
		}
	}
	return b.Bytes()
}

// WriteIndex regenerates INDEX.md, reporting whether the content changed.
func (s *Store) WriteIndex(notes []*Note) (changed bool, err error) {
	want := RenderIndex(notes)
	got, err := os.ReadFile(s.IndexPath()) // #nosec G304 -- reads the store's own generated index
	if err != nil && !errors.Is(err, fs.ErrNotExist) {
		return false, fmt.Errorf("read %s: %w", s.IndexPath(), err)
	}
	if err == nil && bytes.Equal(got, want) {
		return false, nil
	}
	if err := os.WriteFile(s.IndexPath(), want, 0o644); err != nil { // #nosec G306 -- committed source
		return false, fmt.Errorf("write %s: %w", s.IndexPath(), err)
	}
	return true, nil
}

// IndexCurrent reports whether INDEX.md matches what WriteIndex would
// produce for notes.
func (s *Store) IndexCurrent(notes []*Note) (bool, error) {
	got, err := os.ReadFile(s.IndexPath()) // #nosec G304 -- reads the store's own generated index
	if errors.Is(err, fs.ErrNotExist) {
		return false, nil
	}
	if err != nil {
		return false, fmt.Errorf("read %s: %w", s.IndexPath(), err)
	}
	return bytes.Equal(got, RenderIndex(notes)), nil
}
