package tests

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/pedromvgomes/agentic-toolkit/internal/review"
)

// The patch parsers key off the `a/` and `b/` header prefixes, and a
// developer's own git configuration can rewrite or remove them. Reading the
// change would then find nothing to read and say so in no way at all.
func TestPatchParsingSurvivesTheInvokersGitConfig(t *testing.T) {
	for _, cfg := range [][2]string{
		{"diff.noprefix", "true"},
		{"diff.mnemonicPrefix", "true"},
		{"core.quotePath", "true"},
	} {
		t.Run(cfg[0], func(t *testing.T) {
			// Committed at the base and modified here: an untracked file is
			// read straight off disk and would never reach `git diff`, which
			// is where the header form these parsers depend on is decided.
			r := newRepo(t)
			r.write("worker.go", "package main\n\nfunc F() {}\n")
			base := r.commit("base")
			r.git("config", cfg[0], cfg[1])

			r.write("worker.go", "package main\n\nimport \"sync\"\n\nvar mu sync.Mutex\n\nfunc F() {}\n")
			p := buildProfile(t, r, base)

			if has, _ := p.Signals.Has(review.SignalConcurrency); !has {
				t.Errorf("%s=%s turned signal detection off; signals were %s", cfg[0], cfg[1], p.Signals)
			}
		})
	}
}

// `--` ends option parsing; it does not end pathspec magic. A file the branch
// under review names `:(exclude)<path>` would otherwise drop that path from
// the patch every detector reads, letting the author of a change choose how
// deeply it is reviewed.
func TestAPathspecMagicFilenameCannotHideACodeFile(t *testing.T) {
	profileWith := func(t *testing.T, extra string) *review.Profile {
		t.Helper()
		// Both files are committed at the base and modified here. The pathspec
		// only reaches git for a tracked file; an untracked one is read off
		// disk and would sidestep the very argument under test.
		r := newRepo(t)
		r.write("worker.go", "package main\n\nfunc F() {}\n")
		if extra != "" {
			r.write(extra, "x\n")
		}
		base := r.commit("base")

		r.write("worker.go", "package main\n\nimport \"sync\"\n\nvar mu sync.Mutex\n\nfunc F() {}\n")
		if extra != "" {
			r.write(extra, "y\n")
		}
		return buildProfile(t, r, base)
	}

	control := profileWith(t, "")
	attack := profileWith(t, ":(exclude)worker.go")

	if has, _ := control.Signals.Has(review.SignalConcurrency); !has {
		t.Fatalf("the control case must detect concurrency for this test to mean anything; got %s", control.Signals)
	}
	if has, _ := attack.Signals.Has(review.SignalConcurrency); !has {
		t.Errorf("a file named `:(exclude)worker.go` hid worker.go from the review; signals were %s", attack.Signals)
	}
}

// Batch responses are matched to requests positionally, so a record boundary
// must be impossible to forge from a path. A deleted file is absent at the
// head, which is what makes its record a bodiless one — the case where a
// forged boundary shifts every later file's content onto the wrong file.
func TestFileHeadsKeepsPathsAndBodiesTogether(t *testing.T) {
	r := newRepo(t)
	r.write("a.go", "package a\n")
	r.write("b.go", "// Code generated by tool. DO NOT EDIT.\n\npackage b\n")
	r.write("c.go", "package c\n")
	rev := r.commit("base")

	heads := review.FileHeads(r.dir, rev, []string{"gone.go", "a.go", "b.go", "c.go"}, 4096)

	if _, ok := heads["gone.go"]; ok {
		t.Error("a path absent at the revision was given a body")
	}
	for path, want := range map[string]string{
		"a.go": "package a\n",
		"b.go": "// Code generated by tool. DO NOT EDIT.",
		"c.go": "package c\n",
	} {
		if !strings.HasPrefix(heads[path], want) {
			t.Errorf("heads[%q] = %q, want it to start with %q", path, heads[path], want)
		}
	}
}

// A generated-marker classification is a per-file answer, so one path that
// cannot be read must not cost every later file its answer.
func TestOneUnreadablePathDoesNotCostTheRestTheirHeads(t *testing.T) {
	r := newRepo(t)
	r.write("real.go", "package real\n")
	rev := r.commit("base")

	heads := review.FileHeads(r.dir, rev, []string{"gone one.go", "gone two.go", "real.go"}, 4096)

	if got := heads["real.go"]; !strings.HasPrefix(got, "package real") {
		t.Errorf("heads[real.go] = %q; two absent paths before it cost it its head", got)
	}
}

// git quotes a name it considers unusual. Unquoting rather than skipping is
// what lets a file whose name carries a tab be reviewed instead of dropped.
func TestAQuotedFilenameIsStillReviewed(t *testing.T) {
	// Committed at the base and modified here: only a tracked file's name
	// travels through a diff header, which is where git quotes it.
	r := newRepo(t)
	r.write("od\td.go", "package main\n\nfunc F() {}\n")
	base := r.commit("base")

	r.write("od\td.go", "package main\n\nimport \"sync\"\n\nvar mu sync.Mutex\n\nfunc F() {}\n")
	p := buildProfile(t, r, base)

	if has, _ := p.Signals.Has(review.SignalConcurrency); !has {
		t.Errorf("a file whose name git quotes was skipped; signals were %s", p.Signals)
	}
}

// Both spellings git reports for each attribute are honoured: `a linguist-generated`
// yields `set`, and `a linguist-generated=true` — Linguist's own documented
// form — yields `true`.
func TestGitattributesValueSpellings(t *testing.T) {
	r := newRepo(t)
	for _, name := range []string{"bare.ts", "explicit.ts", "nodiff.ts", "hand.ts"} {
		r.write(name, "export const a = 1\n")
	}
	r.write(".gitattributes", "bare.ts linguist-generated\nexplicit.ts linguist-generated=true\nnodiff.ts diff=false\n")
	base := r.commit("base")

	for _, name := range []string{"bare.ts", "explicit.ts", "nodiff.ts", "hand.ts"} {
		r.write(name, "export const a = 2\n")
	}
	p := buildProfile(t, r, base)

	for _, name := range []string{"bare.ts", "explicit.ts", "nodiff.ts"} {
		if got, _ := excludedFor(p, name); got != review.ExcludedGenerated {
			t.Errorf("%s excluded as %q, want generated", name, got)
		}
	}
	if got, _ := excludedFor(p, "hand.ts"); got != review.NotExcluded {
		t.Errorf("hand.ts excluded as %q, want reviewable", got)
	}
}

// A link's target may be a file outside the repository, so its content is not
// read — but the change still contains it, and a profile that omitted it would
// report a file that was added as never having existed.
func TestAnUntrackedSymlinkIsReportedWithoutBeingFollowed(t *testing.T) {
	outside := filepath.Join(t.TempDir(), "secret.txt")
	if err := os.WriteFile(outside, []byte("SECRET-MARKER\n"), 0o600); err != nil {
		t.Fatal(err)
	}

	r := newRepo(t)
	r.write("seed.txt", "x\n")
	base := r.commit("base")

	r.write("real.go", "package main\n")
	if err := os.Symlink(outside, filepath.Join(r.dir, "link.txt")); err != nil {
		t.Skipf("symlinks unavailable: %v", err)
	}

	p := buildProfile(t, r, base)

	got, found := excludedFor(p, "link.txt")
	if !found {
		t.Fatal("the symlink is missing from the change entirely")
	}
	if got != review.ExcludedSymlink {
		t.Errorf("link.txt excluded as %q, want symlink", got)
	}
	for _, f := range p.Files {
		if f.Path == "link.txt" && f.Added != 0 {
			t.Errorf("the symlink's target was read: %d lines", f.Added)
		}
	}
}

// Under -U0 a body line is `+` or `-` followed by whatever the author wrote.
// A removed `-- comment` arrives as `--- comment` and an added line beginning
// `++ ` arrives as `+++ ...`; read as headers, either renames the section and
// credits every following line to a path that does not exist.
func TestABodyLineIsNotAFileHeader(t *testing.T) {
	// The decoy is ADDED, so it reaches the parser with a `+` in front: a line
	// whose content starts with `++ ` arrives as `+++ ...`. Locking is added
	// after it, so if the decoy is read as a header the locking is credited to
	// the invented path and its signal is lost.
	//
	// The removed-comment form clobbers only the pre-image name, which matters
	// for a deletion — covered by the deleted-file case in signal_test.go.
	cases := []struct{ name, decoy string }{
		{"an added line beginning ++", "++ b/hijacked"},
		{"an added line beginning +++", "+++ b/hijacked"},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			r := newRepo(t)
			r.write("worker.go", "package main\n\nfunc F() {}\n")
			base := r.commit("base")

			// The decoy is written raw, not as a comment: it has to reach the
			// parser as `+`+`++ ...`. The file is never compiled — the profile
			// reads lines, it does not build them.
			r.write("worker.go", "package main\n"+tc.decoy+"\nimport \"sync\"\n\nvar mu sync.Mutex\n\nfunc F() {}\n")
			p := buildProfile(t, r, base)

			if has, _ := p.Signals.Has(review.SignalConcurrency); !has {
				t.Errorf("a body line starting %q was read as a file header; signals were %s", tc.decoy, p.Signals)
			}
			for _, h := range review.Hunks(mustPatch(t, r, base)) {
				if h.File != "worker.go" {
					t.Errorf("hunk attributed to %q, want worker.go", h.File)
				}
			}
		})
	}
}

// mustPatch captures the patch the profile reads, for tests that assert on
// how it parses.
func mustPatch(t *testing.T, r *repo, base string) string {
	t.Helper()
	p := buildProfile(t, r, base)
	patch, err := review.Patch(r.dir, base, "", p.ReviewableFiles())
	if err != nil {
		t.Fatalf("Patch: %v", err)
	}
	return patch
}

// A search at a revision reports `<rev>:<path>`; the caller wants the path.
func TestGrepFilesStripsTheRevisionPrefix(t *testing.T) {
	r := newRepo(t)
	r.write("lib.go", "package lib\n\nfunc Widget() {}\n")
	r.write("app.go", "package lib\n\nvar _ = Widget\n")
	rev := r.commit("base")

	files, found := review.GrepFiles(r.dir, rev, "Widget")
	if !found {
		t.Fatal("the search did not run")
	}
	for _, f := range files {
		if strings.Contains(f, ":") {
			t.Errorf("result %q still carries its revision prefix", f)
		}
	}
	if len(files) != 2 {
		t.Errorf("files = %v, want lib.go and app.go", files)
	}
}

// The generated-marker read and the untracked read resolve repo-relative
// names the same way, so they refuse a link the same way. Following one names
// a file outside the repository.
func TestFileHeadsDoesNotFollowASymlink(t *testing.T) {
	outside := filepath.Join(t.TempDir(), "secret.txt")
	if err := os.WriteFile(outside, []byte("// Code generated by tool. DO NOT EDIT.\n"), 0o600); err != nil {
		t.Fatal(err)
	}

	r := newRepo(t)
	r.write("real.go", "package real\n")
	if err := os.Symlink(outside, filepath.Join(r.dir, "link.go")); err != nil {
		t.Skipf("symlinks unavailable: %v", err)
	}
	r.commit("base")

	// An empty rev reads the working tree, which is the path that resolves a
	// name onto disk.
	heads := review.FileHeads(r.dir, "", []string{"link.go", "real.go"}, 4096)

	if body := heads["link.go"]; body != "" {
		t.Errorf("heads[link.go] = %q; the link's target was read", body)
	}
	if !strings.HasPrefix(heads["real.go"], "package real") {
		t.Errorf("heads[real.go] = %q, want the file's own content", heads["real.go"])
	}
}
