package tests

import (
	"fmt"
	"strings"
	"testing"

	"github.com/pedromvgomes/agentic-toolkit/internal/review"
)

func buildProfile(t *testing.T, r *repo, base string) *review.Profile {
	t.Helper()
	p, err := review.BuildProfile(review.ProfileOptions{Dir: r.dir, Base: base})
	if err != nil {
		t.Fatalf("BuildProfile: %v", err)
	}
	return p
}

// excludedFor returns why the named path was excluded, and whether it was in
// the change at all.
func excludedFor(p *review.Profile, path string) (review.Exclusion, bool) {
	for _, f := range p.Files {
		if f.Path == path {
			return f.Excluded, true
		}
	}
	return review.NotExcluded, false
}

// Mechanical bulk is bulk nobody wrote. Sizing a review on it produces a deep
// panel for a dependency bump, which then spends its budget reading a
// lockfile.
func TestMechanicalFilesAreExcluded(t *testing.T) {
	r := newRepo(t)
	r.write("main.go", "package main\n")
	base := r.commit("base")

	r.write("go.sum", "example.com/x v1.0.0 h1:abc=\n")
	r.write("vendor/example.com/x/x.go", "package x\n")
	r.write("api/api.pb.go", "package api\n\ntype T struct{}\n")
	r.write("zz_gen.go", "// Code generated by stringer. DO NOT EDIT.\n\npackage main\n")
	r.write("logo.png", "\x89PNG\r\n\x1a\n\x00\x00binary")
	r.write("main.go", "package main\n\nfunc Run() {}\n")

	p := buildProfile(t, r, base)

	for _, tc := range []struct {
		path string
		want review.Exclusion
	}{
		{"go.sum", review.ExcludedLockfile},
		{"vendor/example.com/x/x.go", review.ExcludedVendored},
		{"api/api.pb.go", review.ExcludedGenerated},
		{"zz_gen.go", review.ExcludedGenerated},
		{"logo.png", review.ExcludedBinary},
	} {
		got, found := excludedFor(p, tc.path)
		if !found {
			t.Errorf("%s is not in the change at all", tc.path)
			continue
		}
		if got != tc.want {
			t.Errorf("%s excluded as %q, want %q", tc.path, got, tc.want)
		}
	}

	if p.ChangedFiles != 1 {
		t.Errorf("reviewable files = %d, want 1 (main.go alone)", p.ChangedFiles)
	}
}

// The repo is a better authority on its own generated trees than any table in
// the binary, so what it marks is honoured — as an addition, since the many
// repos that mark nothing would otherwise get no exclusions at all.
func TestGitattributesMarksGeneratedFiles(t *testing.T) {
	r := newRepo(t)
	r.write("schema.ts", "export const a = 1\n")
	r.write("hand.ts", "export const b = 1\n")
	r.write(".gitattributes", "schema.ts linguist-generated\n")
	base := r.commit("base")

	r.write("schema.ts", "export const a = 2\n")
	r.write("hand.ts", "export const b = 2\n")

	p := buildProfile(t, r, base)

	if got, _ := excludedFor(p, "schema.ts"); got != review.ExcludedGenerated {
		t.Errorf("schema.ts excluded as %q, want generated", got)
	}
	if got, _ := excludedFor(p, "hand.ts"); got != review.NotExcluded {
		t.Errorf("hand.ts excluded as %q, want reviewable", got)
	}
}

// A move is mechanical; an edit inside a move is not. Counting the whole file
// twice for a rename would size a directory reshuffle as a rewrite.
func TestARenameCountsOnlyItsEdits(t *testing.T) {
	r := newRepo(t)
	body := strings.Repeat("line\n", 50)
	r.write("old/pure.go", "package old\n"+body)
	r.write("old/edited.go", "package old\n"+body)
	base := r.commit("base")

	r.mkdir("new")
	r.git("mv", "old/pure.go", "new/pure.go")
	r.git("mv", "old/edited.go", "new/edited.go")
	r.write("new/edited.go", "package old\n"+body+"\nfunc Added() {}\n")
	r.commit("move and edit")

	p, err := review.BuildProfile(review.ProfileOptions{Dir: r.dir, Base: base, Head: "HEAD"})
	if err != nil {
		t.Fatalf("BuildProfile: %v", err)
	}

	if got, _ := excludedFor(p, "new/pure.go"); got != review.ExcludedPureRename {
		t.Errorf("a pure rename was excluded as %q, want pure rename", got)
	}
	if p.ChangedLines > 10 {
		t.Errorf("changed lines = %d; a move plus a two-line edit should count the edit", p.ChangedLines)
	}
	if p.ChangedFiles != 1 {
		t.Errorf("reviewable files = %d, want 1 (the edited one)", p.ChangedFiles)
	}
}

// A working-tree review sees the files the change added. They are untracked,
// so git diff does not know about them, and a profile without them reports a
// smaller change rather than an incomplete one.
func TestUntrackedFilesCount(t *testing.T) {
	r := newRepo(t)
	r.write("main.go", "package main\n")
	base := r.commit("base")

	r.write("added.go", "package main\n\nfunc Added() {}\n")

	p := buildProfile(t, r, base)

	if _, found := excludedFor(p, "added.go"); !found {
		t.Fatal("an untracked file is missing from the change entirely")
	}
	if p.ChangedFiles != 1 || p.ChangedLines != 3 {
		t.Errorf("profile = %d files, %d lines; want the untracked file's 3 lines", p.ChangedFiles, p.ChangedLines)
	}
}

// A signal fires on either evidence: a path that says what the file is, or a
// changed line that says what the change did.
func TestSignalsFireOnPathsAndOnContent(t *testing.T) {
	r := newRepo(t)
	r.write("main.go", "package main\n")
	base := r.commit("base")

	r.write("internal/auth/token.go", "package auth\n")
	r.write("worker.go", "package main\n\nimport \"sync\"\n\nvar mu sync.Mutex\n")

	p := buildProfile(t, r, base)

	for _, want := range []review.Signal{review.SignalAuth, review.SignalConcurrency} {
		if has, ok := p.Signals.Has(want); !has || !ok {
			t.Errorf("signal %s = (%v, known=%v), want present", want, has, ok)
		}
	}
	if has, _ := p.Signals.Has(review.SignalIaC); has {
		t.Error("iac fired on a change with no infrastructure in it")
	}
}

// A comment is prose, and a signal is a claim about what the code does.
func TestASignalDoesNotFireOnAComment(t *testing.T) {
	r := newRepo(t)
	r.write("main.go", "package main\n")
	base := r.commit("base")

	r.write("notes.go", "package main\n\n// This file deliberately holds no sync.Mutex and no crypto.\nfunc F() {}\n")

	p := buildProfile(t, r, base)

	if has, _ := p.Signals.Has(review.SignalConcurrency); has {
		t.Error("concurrency fired on a comment saying the file has none")
	}
}

// Unavailable is never low. A language the toolkit cannot read symbols out of
// has an unknown blast radius, not a small one.
func TestAnUnreadableLanguageMakesTheCountUnavailable(t *testing.T) {
	r := newRepo(t)
	r.write("main.go", "package main\n")
	base := r.commit("base")

	r.write("service.zig", "pub fn main() void {}\n")

	p := buildProfile(t, r, base)

	if _, ok := p.ReferencingFiles.Value(); ok {
		t.Fatalf("referencing files = %s, want unavailable for a language with no extractor", p.ReferencingFiles)
	}
	if !strings.Contains(p.ReferencingFiles.Reason, "unrecognised") {
		t.Errorf("reason = %q, want it to name what could not be read", p.ReferencingFiles.Reason)
	}
}

// A change made only of documentation and configuration has a blast radius of
// zero rather than an unknown one: those formats export nothing other code
// calls, and that is a fact about them rather than a gap in the toolkit.
func TestFormatsThatExportNothingStillCount(t *testing.T) {
	r := newRepo(t)
	r.write("main.go", "package main\n")
	base := r.commit("base")

	r.write("README.md", "# Title\n")
	r.write("config.yaml", "key: value\n")

	p := buildProfile(t, r, base)

	n, ok := p.ReferencingFiles.Value()
	if !ok {
		t.Fatalf("referencing files = %s, want an available zero", p.ReferencingFiles)
	}
	if n != 0 {
		t.Errorf("referencing files = %d, want 0", n)
	}
}

// The count measures how widely used the changed code is.
func TestReferencingFilesCountsDownstreamUsers(t *testing.T) {
	r := newRepo(t)
	r.write("lib/lib.go", "package lib\n\nfunc Widget() {}\n")
	for _, name := range []string{"a", "b", "c"} {
		r.write("app/"+name+".go", "package app\n\nimport \"lib\"\n\nvar _ = lib.Widget\n")
	}
	base := r.commit("base")

	r.write("lib/lib.go", "package lib\n\nfunc Widget() int { return 1 }\n")

	p := buildProfile(t, r, base)

	n, ok := p.ReferencingFiles.Value()
	if !ok {
		t.Fatalf("referencing files = %s, want a count", p.ReferencingFiles)
	}
	if n != 3 {
		t.Errorf("referencing files = %d, want 3 — the files using the symbol, not the one defining it", n)
	}
}

// fix-revert asks whether these lines were written by a repair, not whether
// this file has ever been repaired — which is true of nearly every file in a
// mature repo and would make the signal fire always.
func TestFixRevertTracesLinesNotFiles(t *testing.T) {
	// The two functions sit far apart so git produces a separate hunk for
	// each. Two edits close enough to share a hunk share its history too,
	// which is what a hunk means.
	gap := strings.Repeat("\n", 40)
	svc := func(repaired, ordinary string) string {
		return "package svc\n\nfunc Repaired() {" + repaired + "}\n" + gap + "func Ordinary() {" + ordinary + "}\n"
	}

	r := newRepo(t)
	r.write("svc.go", svc("", ""))
	r.commit("feat: add the service")

	r.write("svc.go", svc(" guard() ", ""))
	base := r.commit("fix: guard the nil dereference")

	t.Run("undoing the repaired line fires", func(t *testing.T) {
		r.write("svc.go", svc("", ""))
		p := buildProfile(t, r, base)
		if has, ok := p.Signals.Has(review.SignalFixRevert); !has || !ok {
			t.Errorf("fix-revert = (%v, known=%v), want present", has, ok)
		}
	})

	t.Run("editing an untouched line does not", func(t *testing.T) {
		r.write("svc.go", svc(" guard() ", " work() "))
		p := buildProfile(t, r, base)
		if has, _ := p.Signals.Has(review.SignalFixRevert); has {
			t.Error("fix-revert fired on lines no repair ever wrote")
		}
	})
}

// A budget that ran out is not evidence that nothing was undone.
func TestAnExhaustedBlameBudgetLeavesTheSignalUndetermined(t *testing.T) {
	r := newRepo(t)
	r.write("a.go", "package a\n\nfunc A() {}\n")
	r.write("b.go", "package b\n\nfunc B() {}\n")
	base := r.commit("base")

	r.write("a.go", "package a\n\nfunc A() int { return 1 }\n")
	r.write("b.go", "package b\n\nfunc B() int { return 2 }\n")

	p, err := review.BuildProfile(review.ProfileOptions{Dir: r.dir, Base: base, BlameBudget: 1})
	if err != nil {
		t.Fatalf("BuildProfile: %v", err)
	}

	has, known := p.Signals.Has(review.SignalFixRevert)
	if has || known {
		t.Fatalf("fix-revert = (%v, known=%v), want undetermined", has, known)
	}
	if !strings.Contains(p.Signals.Undetermined(review.SignalFixRevert), "budget") {
		t.Errorf("reason = %q, want it to say the budget ran out", p.Signals.Undetermined(review.SignalFixRevert))
	}
}

// A test declares plenty of exported-looking names and not one of them is
// reachable from anywhere. Counting them fills the symbol budget with names
// that have exactly one referencing file, which turns a blast-radius measure
// into a count of how many tests a change added.
func TestSymbolsAreNotTakenFromTestFiles(t *testing.T) {
	r := newRepo(t)
	r.write("lib/lib.go", "package lib\n\nfunc Widget() {}\n")
	for _, name := range []string{"a", "b", "c"} {
		r.write("app/"+name+".go", "package app\n\nimport \"lib\"\n\nvar _ = lib.Widget\n")
	}
	base := r.commit("base")

	r.write("lib/lib.go", "package lib\n\nfunc Widget() int { return 1 }\n")
	r.write("lib/lib_test.go", "package lib\n\nimport \"testing\"\n\nfunc TestWidget(t *testing.T) { Widget() }\n")

	p := buildProfile(t, r, base)

	for _, sym := range p.Symbols {
		if strings.HasPrefix(sym, "Test") {
			t.Errorf("symbols include %q, taken from a test file: %v", sym, p.Symbols)
		}
	}
	// The test file is still part of the change; only its symbols are skipped.
	if _, found := excludedFor(p, "lib/lib_test.go"); !found {
		t.Error("the test file should still count as a reviewable file")
	}
	if n, _ := p.ReferencingFiles.Value(); n != 3 {
		t.Errorf("referencing files = %d, want 3 — the count is not diluted by the test", n)
	}
}

// The pathspec that scopes the patch carries both names of a renamed file.
// Given only the destination, git has nothing to pair it with and reports the
// move as a wholly new file — so unchanged code arrives wearing the change's
// name, and signals and symbols are read out of lines nobody touched.
func TestARenameDoesNotReportUntouchedCode(t *testing.T) {
	r := newRepo(t)
	r.write("old.go", "package p\n\nimport \"sync\"\n\nvar mu sync.Mutex\n\nfunc Widget() {}\n")
	base := r.commit("base")

	r.git("mv", "old.go", "new.go")
	r.write("new.go", "package p\n\nimport \"sync\"\n\nvar mu sync.Mutex\n\nfunc Widget() {}\n// a note\n")
	r.commit("move and comment")

	p, err := review.BuildProfile(review.ProfileOptions{Dir: r.dir, Base: base, Head: "HEAD"})
	if err != nil {
		t.Fatalf("BuildProfile: %v", err)
	}

	if has, _ := p.Signals.Has(review.SignalConcurrency); has {
		t.Errorf("concurrency fired on locking the change never touched; signals were %s", p.Signals)
	}
	if len(p.Symbols) != 0 {
		t.Errorf("symbols = %v, want none — the change declares nothing", p.Symbols)
	}
	if p.ChangedLines > 4 {
		t.Errorf("changed lines = %d; a move plus one comment is not a rewrite", p.ChangedLines)
	}
}

// The reference count is taken at the revision under review. Searching the
// working tree instead would make a fixed commit range's answer move whenever
// an unrelated uncommitted edit did.
func TestTheReferenceCountIsTakenAtTheReviewedRevision(t *testing.T) {
	r := newRepo(t)
	r.write("lib/lib.go", "package lib\n\nfunc Widget() {}\n")
	for i := 0; i < 5; i++ {
		r.write(fmt.Sprintf("app/a%d.go", i), "package app\n\nvar _ = Widget\n")
	}
	base := r.commit("base")
	r.write("lib/lib.go", "package lib\n\nfunc Widget() int { return 1 }\n")
	r.commit("change")

	atHead := func() int {
		t.Helper()
		p, err := review.BuildProfile(review.ProfileOptions{Dir: r.dir, Base: base, Head: "HEAD"})
		if err != nil {
			t.Fatalf("BuildProfile: %v", err)
		}
		n, ok := p.ReferencingFiles.Value()
		if !ok {
			t.Fatalf("referencing files unavailable: %s", p.ReferencingFiles.Reason)
		}
		return n
	}

	before := atHead()
	for i := 0; i < 5; i++ {
		r.write(fmt.Sprintf("app/a%d.go", i), "package app\n")
	}
	if after := atHead(); after != before {
		t.Errorf("count moved from %d to %d because of uncommitted edits outside the range", before, after)
	}
}

// A search that did not run is not a count of zero. Reading it as one makes a
// referencing_files escalation silently never fire.
func TestASearchThatCannotRunIsNotACountOfZero(t *testing.T) {
	r := newRepo(t)
	r.write("lib.go", "package lib\n")
	r.commit("base")

	if _, found := review.GrepFiles(r.dir, "no-such-revision", "Widget"); found {
		t.Error("GrepFiles reported a result for a revision that does not exist")
	}
	if _, found := review.GrepFiles(r.dir, "", "NothingMatchesThis"); !found {
		t.Error("GrepFiles reported no search for a search that ran and matched nothing")
	}
}
