// Package completioninstall writes a shell-completion script for agtk to
// a path the user's shell will actually load from. It mirrors the
// install_completion logic in install.sh so that `agtk update` keeps
// completions in sync after a self-replace, not just fresh installs.
//
// Path strategy (matches install.sh):
//
//   - zsh: $(brew --prefix)/share/zsh/site-functions/_agtk when brew is
//     available and the dir is writable; otherwise ~/.zsh/completions/_agtk
//     with an fpath hint.
//   - bash: ~/.local/share/bash-completion/completions/agtk.
//   - fish: ~/.config/fish/completions/agtk.fish.
//
// The completion script itself is generated by shelling out to the
// running binary's own `completion <shell>` subcommand (cobra-provided),
// which means callers should invoke Install *after* a self-update so
// the new binary's command tree is what gets emitted.
package completioninstall

import (
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// Result describes the outcome of an Install call. Skipped=true means
// no file was written; Reason explains why (disabled, unsupported
// shell, missing $HOME). On a successful write, Path is the file and
// Note is a one-line hint for the user (e.g. "restart your shell").
type Result struct {
	Skipped bool
	Reason  string
	Shell   string
	Path    string
	Note    string
}

// Options carries the inputs and test seams. All fields are optional;
// defaults read from the live process environment.
type Options struct {
	// Disabled short-circuits the install (used for AGTK_NO_COMPLETION
	// and --no-completion).
	Disabled bool

	// Binary is the executable name (e.g. "agtk"). Empty = "agtk".
	Binary string

	// Shell, when non-empty, overrides $SHELL detection. Bare name
	// ("zsh"), not a path.
	Shell string

	// Home, when non-empty, overrides $HOME.
	Home string

	// Executable, when non-empty, is the path to the binary used to
	// generate the completion script. Empty = os.Executable().
	Executable string

	// BrewPrefix, when non-nil, returns the brew prefix (or "" when
	// brew is unavailable). Defaults to running `brew --prefix`.
	BrewPrefix func() string

	// Run, when non-nil, executes the binary's completion subcommand
	// and returns its stdout. Defaults to exec.Command(exe, "completion",
	// shell).Output().
	Run func(exe, shell string) ([]byte, error)

	// WriteFile, when non-nil, replaces os.WriteFile (after MkdirAll
	// of the parent). Tests inject this to assert on writes.
	WriteFile func(path string, data []byte) error
}

// Install resolves the right completion path for the user's shell,
// generates the completion script via the binary's own `completion`
// subcommand, and writes it to disk. The Result is also rendered to
// stdout (path + note) so callers can give the user the same feedback
// install.sh does.
//
// All errors are wrapped with enough context for the caller to surface
// them as a hint without aborting the larger flow.
func Install(stdout io.Writer, opts Options) (Result, error) {
	if opts.Disabled {
		return Result{Skipped: true, Reason: "disabled"}, nil
	}

	bin := opts.Binary
	if bin == "" {
		bin = "agtk"
	}

	shell := opts.Shell
	if shell == "" {
		shell = detectShell(os.Getenv("SHELL"))
	}
	if shell == "" {
		return Result{Skipped: true, Reason: "shell not detected"}, nil
	}
	if !supportedShell(shell) {
		return Result{Skipped: true, Reason: "unsupported shell: " + shell, Shell: shell}, nil
	}

	home := opts.Home
	if home == "" {
		home = os.Getenv("HOME")
	}
	if home == "" {
		return Result{Skipped: true, Reason: "no $HOME"}, nil
	}

	brewPrefix := ""
	if shell == "zsh" {
		bp := opts.BrewPrefix
		if bp == nil {
			bp = defaultBrewPrefix
		}
		brewPrefix = bp()
	}

	path, note := resolvePath(shell, bin, home, brewPrefix)
	if path == "" {
		return Result{Skipped: true, Reason: "no path for shell: " + shell, Shell: shell}, nil
	}

	exe := opts.Executable
	if exe == "" {
		var err error
		exe, err = os.Executable()
		if err != nil {
			return Result{Shell: shell}, fmt.Errorf("locate self: %w", err)
		}
	}

	run := opts.Run
	if run == nil {
		run = defaultRun
	}
	script, err := run(exe, shell)
	if err != nil {
		return Result{Shell: shell, Path: path}, fmt.Errorf("generate %s completion: %w", shell, err)
	}

	write := opts.WriteFile
	if write == nil {
		write = defaultWriteFile
	}
	if err := write(path, script); err != nil {
		return Result{Shell: shell, Path: path}, fmt.Errorf("write %s: %w", path, err)
	}

	res := Result{Shell: shell, Path: path, Note: note}
	if stdout != nil {
		fmt.Fprintf(stdout, "installed %s completion → %s\n", shell, path)
		if note != "" {
			fmt.Fprintf(stdout, "  note: %s\n", note)
		}
	}
	return res, nil
}

// detectShell returns the bare shell name from a $SHELL value (e.g.
// "/bin/zsh" → "zsh"). Empty input → empty output.
func detectShell(shellEnv string) string {
	if shellEnv == "" {
		return ""
	}
	return filepath.Base(shellEnv)
}

func supportedShell(shell string) bool {
	switch shell {
	case "bash", "zsh", "fish":
		return true
	}
	return false
}

// resolvePath picks the on-disk location for the completion script and
// returns a one-line note for the user. brewPrefix is consulted only
// for zsh and only when the corresponding site-functions dir is
// writable; pass "" when brew is unavailable.
func resolvePath(shell, binary, home, brewPrefix string) (path, note string) {
	switch shell {
	case "zsh":
		if brewPrefix != "" {
			site := filepath.Join(brewPrefix, "share", "zsh", "site-functions")
			if dirWritable(site) {
				return filepath.Join(site, "_"+binary), "restart your shell (e.g. 'exec zsh') to load completions"
			}
		}
		return filepath.Join(home, ".zsh", "completions", "_"+binary),
			"add 'fpath=(~/.zsh/completions $fpath)' to ~/.zshrc before 'compinit', then restart your shell"
	case "bash":
		return filepath.Join(home, ".local", "share", "bash-completion", "completions", binary),
			"ensure the bash-completion package is installed; restart your shell to load"
	case "fish":
		return filepath.Join(home, ".config", "fish", "completions", binary+".fish"),
			"fish auto-loads from this directory; new shells pick it up immediately"
	}
	return "", ""
}

func dirWritable(dir string) bool {
	info, err := os.Stat(dir)
	if err != nil || !info.IsDir() {
		return false
	}
	probe, err := os.CreateTemp(dir, ".agtk-write-probe-")
	if err != nil {
		return false
	}
	name := probe.Name()
	probe.Close()
	os.Remove(name)
	return true
}

func defaultBrewPrefix() string {
	out, err := exec.Command("brew", "--prefix").Output()
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(out))
}

func defaultRun(exe, shell string) ([]byte, error) {
	return exec.Command(exe, "completion", shell).Output()
}

func defaultWriteFile(path string, data []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, data, 0o644)
}
